apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-http-index
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: crun
      timeoutSeconds: 1
      containers:
      - name: http-server-noop
        image: docker.io/adroitx/http-server-index:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 1234