apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-http-fib
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: crun
      timeoutSeconds: 1
      containers:
      - name: http-server-fib
        image: docker.io/adroitx/http-server-fib:latest
        resources:
            limits:
              cpu: 4
        imagePullPolicy: Always
        ports:
        - containerPort: 1234
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 1234